<script language="php>
	echo 'This is some text generated by PHP.';
</script>

<p>Or you can try this: </p>

<%
	echo 'This is some text generated by PHP(2).';
%>

<p> in PHP 6 ASP-style tags are no longer supported. " <% echo 'stuff in here'; %> "</p>
