<?php
	echo '<p>This is some text.</p>';
?>
<p>Some of this text is static/plain html, <?php echo 'but this is not!'; ?></p>
<?php echo '<p>'; ?>
This text is enclosed in paragraph tags that are being generated by PHP code.
<?php echo '</p>'; ?>
